In [2]:
## Numpy ( numerical for Python)
# It will provide more efficent storage and Data operation as size grows
#NumPy’s main object is the homogeneous multidimensional array.
import numpy as np


In [3]:
a = np.arange(15)

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.ndim

1

In [7]:
a.dtype.name

'int32'

In [9]:
a.itemsize
a.size

15

In [6]:
a[1:3]

array([1, 2])

In [11]:
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
a[4]

4

In [13]:
a[8]

8

In [9]:
# Reverse the order of array
a[::-2]

array([14, 12, 10,  8,  6,  4,  2,  0])

In [10]:
x = a.reshape(3,5)

In [14]:
x[2]

array([10, 11, 12, 13, 14])

In [19]:
# two rows and three columns
x[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [20]:
# three rows and two colums
x[:3, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])